Fix hugo BUILD Warning and Error causing Netlify to fail

Building sites … WARN 2019/06/16 15:46:53 Page's .Hugo is deprecated and will be removed in a future release. Use the global hugo function.
WARN 2019/06/16 15:46:53 Page's .URL is deprecated and will be removed in a future release. Use .Permalink or .RelPermalink. If what you want is the front matter URL value, use .Params.url.
WARN 2019/06/16 15:46:53 make non-relative ref/relref page reference(s) in page %q absolute, e.g. {{< ref "/blog/my-post.md" >}}
ERROR 2019/06/16 15:46:53 asciidoctor / asciidoc not found in $PATH: Please install.
                  Leaving AsciiDoc content unrendered.